// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-3CyosI-1RdmiPgDF07AVEkYX5_R1N0o',
    appId: '1:220709150346:android:57776204c00fc7cbbf5773',
    messagingSenderId: '220709150346',
    projectId: 'flutter-ec8ec',
    databaseURL: 'https://flutter-ec8ec-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-ec8ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnm4k5CgvaW5DD0yurTSMVf7R6eLw8waI',
    appId: '1:220709150346:ios:0d8e52402ba2921bbf5773',
    messagingSenderId: '220709150346',
    projectId: 'flutter-ec8ec',
    databaseURL: 'https://flutter-ec8ec-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-ec8ec.firebasestorage.app',
    iosBundleId: 'com.example.contador',
  );
}
